=== jjkoletar/fll-sw/src/resources/fll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns=""
            elementFormDefault="qualified" >
  <xsd:element name="fll">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Performance" />
        <xsd:element ref="subjectiveCategory" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="title" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Performance">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:sequence maxOccurs="unbounded">
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="goal" maxOccurs="unbounded" />
          </xsd:sequence>
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="restriction" maxOccurs="unbounded" />
          </xsd:sequence>
          <xsd:element ref="tiebreaker" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>
      </xsd:sequence>
      <xsd:attribute name="minimumScore" type="xsd:integer" default="0">
        <xsd:annotation>
          <xsd:documentation>minimum score allowed in the performance scoring</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="weight" type="xsd:float" default="1.0">
        <xsd:annotation>
          <xsd:documentation>
	    Weight this category has.  Should be a number between 0 and 1.
	  </xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="subjectiveCategory">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
          <xsd:element ref="goal" maxOccurs="unbounded" />
        </xsd:sequence>
      </xsd:sequence>
      <xsd:attribute name="name" type="databaseName" use="required" />
      <xsd:attribute name="title" type="xsd:string" use="required" />

      <xsd:attribute name="weight" type="xsd:float" default="1.0">
        <xsd:annotation>
          <xsd:documentation>
	    Weight this category has.  Should be a number between 0 and 1.
	  </xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="goal">
    <xsd:annotation>
      <xsd:documentation>
        A goal is something that the team may be scored on.  A goal has a
        maximum and a minimum that define what values are allowed.  It also
        has a multiplier for cases where this goal is used to count things.
        If there are no value child elements, then the score is determined
        by multiplying the count, in the range min to max, by the
        multiplier.  If there are child elements, the score is the score
        associated with the choosen child element times the multiplier.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="value" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="score" type="xsd:integer" default="0">
              <xsd:annotation>
                <xsd:documentation>
                  The score one gets for this value of an enumerated goal.
                </xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="title" type="xsd:string" use="required">
              <xsd:annotation>
                <xsd:documentation>
                  The title to display for this value.
                </xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="value" type="xsd:string" use="required">
              <xsd:annotation>
                <xsd:documentation>
                  The value to store in the database for this value.
                </xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" type="databaseID" use="required" />

      <xsd:attribute name="title" type="xsd:string" use="required" />

      <xsd:attribute name="description" type="xsd:string" />

      <xsd:attribute name="min" type="xsd:integer" default="0">
        <xsd:annotation>
	  <xsd:documentation>ignored if enumerated values exist</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="max" type="xsd:integer" default="1">
        <xsd:annotation>
	  <xsd:documentation>ignored if enumerated values exist</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="multiplier" type="xsd:integer" default="1">
        <xsd:annotation>
	  <xsd:documentation>ignored for subjective goals</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="initialValue" type="xsd:integer" default="0">
        <xsd:annotation>
	  <xsd:documentation>ignored for subjective goals</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="restriction">
    <xsd:annotation>
      <xsd:documentation>lower bound and upper bound are inclusive</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="term" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="lowerBound" type="xsd:integer" default="-512" />
      <xsd:attribute name="upperBound" type="xsd:integer" default="512" />
      <xsd:attribute name="message" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="term">
    <xsd:complexType>
      <xsd:attribute name="coefficient" type="xsd:integer" default="1" />
      <xsd:attribute name="goal" type="xsd:IDREF" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tiebreaker">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="test" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="term" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="winner" type="highlow" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="databaseName">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\p{L}[\p{L}\p{Nd}_]*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="databaseID">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="\p{L}[\p{L}\p{Nd}_]*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="highlow">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="high" />
      <xsd:enumeration value="low" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== jjkoletar/fll-sw/src/resources/challenge-region-2003.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="fll.xsd"
     title="FLL 2002 Challenge: Mission Mars" >

  <Performance weight="0.25">

    <goal name="exit_base"
	  title="Exit the Tetrahedron Base"
	  multiplier="39" />

    <goal name="launch_canister"
	  title="Launch the Sample Canister">
      <value score="39" title="Canister Launched" value="launched" />
      <value score="27" title="Launcher Actived Empty" value="empty" />
      <value score="0" title="Canister Not Launched" value="zero" />
    </goal>

    <goal name="clear_solar"
	  title="Clear the Solar Panel">
      <value score="43" title="Dust Completly Cleared" value="completly" />
      <value score="31" title="Dust Partially Cleared" value="partially" />
      <value score="0" title="Dust Not Cleared" value="zero" />
    </goal>

    <goal name="habitation_modules"
	  title="Connect the 180 and 90 Habitation Modules">
      <value score="49" title="V-Shaped Module Connection" value="v" />
      <value score="31" title="Two Module Connections In Line" value="two" />
      <value score="27" title="One Module Connection" value="one" />
      <value score="0" title="Zero Module Connections" value="zero" />
    </goal>

    <goal name="alliance_habitation"
	  title="Complete the Alliance Habitation Module"
	  multiplier="43" />

    <goal name="free_rover"
	  title="Free the Rover">
      <value score="43" title="Rover In Base" value="base" />
      <value score="31" title="Rover Off Dune + On Wheels" value="wheels" />
      <value score="0" title="Rover not Freed" value="zero" />
    </goal>

    <goal name="ice_core"
	  title="Move Ice Cores to Base">
      <value score="49" title="3 Ice Cores in Base" value="three" />
      <value score="31" title="2 Ice Cores in Base" value="two" />
      <value score="27" title="1 Ice Core in Base" value="one" />
      <value score="0" title="0 Ice Cores in Base" value="zero" />
    </goal>

    <goal name="boulders_outside_circle"
	  title="Boulders On the Field Outside The Launch Circle"
          max="4"
	  multiplier="8"
          initialValue="2" />

    <goal name="boulders_in_circle"
	  title="Boulders In The Launch Circle"
          max="4"
	  multiplier="14"
          initialValue="2" />

    <goal name="vehicle"
	  title="All Terrain Vehicle Test"
	  multiplier="39" />

    <restriction lowerBound="0"
		 upperBound="4"
                 message="There are a maximum of 4 boulders on the table"
                 >
      <term goal="boulders_in_circle" />
      <term goal="boulders_outside_circle" />
    </restriction>

    <goal name="Interference"
	  title="Did the team deliberately interfere with the other team?"
	  multiplier="0" />

    <tiebreaker>
      <test goal="Interference" winner="low" />
    </tiebreaker>

  </Performance>

  <subjectiveCategory name="InnovativeDesign"
                      title="Innovative Design"
                      weight="0.0"
                      >
    <goal name="inFunction"
          title="Creativity in Function"
          min="1"
          max="20" />
    <goal name="Uniqueness"
          title="Uniqueness"
          min="1"
          max="20" />
    <goal name="inDesignProcess"
          title="Creativity in Design Process"
          min="1"
          max="20" />
    <goal name="inDesignAndAppearance"
          title="Creativity in Design and Appearance"
          min="1"
          max="20" />
    <goal name="OverallCreativity"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="RobustDesign"
                      title="Robust Design"
                      weight="0.125"
                      >
    <goal name="Structural"
          title="Structural Design"
          min="1"
          max="20" />
    <goal name="Locomotion"
          title="Locomotion"
          min="1"
          max="20" />
    <goal name="Manipulation"
          title="Manipulation"
          min="1"
          max="20" />
    <goal name="Navigation"
          title="Navigation"
          min="1"
          max="20" />
    <goal name="OverallDesign"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>


  <subjectiveCategory name="Presentation"
                      title="Presentation"
                      weight="0.25"
                      >
    <goal name="Research"
          title="Research"
          min="1"
          max="20" />
    <goal name="Knowledge"
          title="Knowldege"
          min="1"
          max="20" />
    <goal name="ChallengeSpecific"
          title="Challenge Specific"
          min="1"
          max="20" />
    <goal name="PresentationInGeneral"
          title="In General"
          min="1"
          max="20" />
    <goal name="Presentation"
          title="Presentation"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Programming"
                      title="Programming"
                      weight="0.125"
                      >
    <goal name="Language"
          title="Language used">
      <value title="RIS" value="ris" />
      <value title="RoboLab" value="robolab" />
      <value title="Unknown" value="unknown" />
    </goal>
    <goal name="UseOfLanguage"
          title="Use of language"
          min="1"
          max="20" />
    <goal name="Modularity"
          title="Modularity/Absraction"
          min="1"
          max="20" />
    <goal name="SensorControl"
          title="Sensor Control"
          min="1"
          max="20" />
    <goal name="Design"
          title="Design"
          min="1"
          max="20" />
    <goal name="ProgrammingInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Teamwork"
                      title="Teamwork"
                      weight="0.25"
                      >
    <goal name="TeamIntegration"
          title="Team Integration"
          min="1"
          max="20" />
    <goal name="Respect"
          title="Respect"
          min="1"
          max="20" />
    <goal name="FocusedEffort"
          title="Focused Effort"
          min="1"
          max="20" />
    <goal name="Consideration"
          title="Participation"
          min="1"
          max="20" />
    <goal name="DecisionSolving"
          title="Decision Making and Problem Solving"
          min="1"
          max="20" />
  </subjectiveCategory>

</fll>

=== jjkoletar/fll-sw/src/resources/challenge-region-2004.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="fll.xsd"
     title="FLL 2004 Challenge: No Limits" >

  <Performance weight="1.0">

    <goal name="serve_dinner"
	  title="Serve Dinner">
      <value score="45" title="Full" value="full" />
      <value score="35" title="Partial" value="partial" />
    </goal>

    <goal name="open_gate"
	  title="Open the Gate">
      <value score="35" title="Full" value="full" />
      <value score="20" title="Partial" value="partial" />
    </goal>

    <goal name="play_ball"
	  title="Each Ball in Your Side of Basket"
          max="16"
          multiplier="5" />

    <goal name="ball_center"
          title="Your Ball in Center Ring"
          multiplier="50" />

    <goal name="bonus"
	  title="Bonus: Each Ball in Your Side NOT in the Basket"
          max="16"
          multiplier="2" />

    <restriction lowerBound="0"
		 upperBound="16"
                 message="There are a maximum of 8 balls on the table"
                 >
      <term goal="play_ball" />
      <term goal="bonus" />
    </restriction>

    <goal name="push_chairs"
	  title="Push in the Chairs"
          max="3"
          multiplier="10" />

    <goal name="read_sign"
	  title="Read the Bus Route Signs"
          multiplier="35" />

    <goal name="cd"
	  title="Put the CD Away">
      <value score="40" title="Full" value="full" />
      <value score="35" title="Partial" value="partial" />
    </goal>

    <goal name="feed_pets"
	  title="Feed the Pets"
          max="3"
          multiplier="15" />

     <goal name="remove_glasses"
           title="Remove the Glasses"
           multiplier="40" />

    <goal name="climb_stairs"
	  title="Climb the Stairs">
      <value score="45" title="Full" value="full" />
      <value score="40" title="Partial" value="partial" />
    </goal>

    <tiebreaker>
      <test goal="climb_stairs" winner="high" />
    </tiebreaker>

  </Performance>

  <subjectiveCategory name="InnovativeDesign"
                      title="Innovative Design"
                      weight="0.0"
                      >
    <goal name="inFunction"
          title="Creativity in Function"
          min="1"
          max="20" />
    <goal name="Uniqueness"
          title="Uniqueness"
          min="1"
          max="20" />
    <goal name="inDesignProcess"
          title="Creativity in Design Process"
          min="1"
          max="20" />
    <goal name="inDesignAndAppearance"
          title="Creativity in Design and Appearance"
          min="1"
          max="20" />
    <goal name="OverallCreativity"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="RobustDesign"
                      title="Robust Design"
                      weight="0.5"
                      >
    <goal name="Structural"
          title="Structural Design"
          min="1"
          max="20" />
    <goal name="Locomotion"
          title="Locomotion"
          min="1"
          max="20" />
    <goal name="Manipulation"
          title="Manipulation"
          min="1"
          max="20" />
    <goal name="Navigation"
          title="Navigation"
          min="1"
          max="20" />
    <goal name="OverallDesign"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>


  <subjectiveCategory name="ResearchPresentation"
                      title="Research Presentation"
                      weight="1.0"
                      >
    <goal name="Research"
          title="Research"
          min="1"
          max="20" />
    <goal name="Knowledge"
          title="Knowldege"
          min="1"
          max="20" />
    <goal name="ChallengeSpecific"
          title="Challenge Specific"
          min="1"
          max="20" />
    <goal name="Presentation"
          title="Presentation"
          min="1"
          max="20" />
    <goal name="Innovation"
          title="Innovation"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Programming"
                      title="Programming"
                      weight="0.5"
                      >
    <goal name="UseOfLanguage"
          title="Use of Language"
          min="1"
          max="20" />
    <goal name="Modularity"
          title="Modularity/Abstraction"
          min="1"
          max="20" />
    <goal name="SensorControl"
          title="Sensor Control"
          min="1"
          max="20" />
    <goal name="Design"
          title="Design"
          min="1"
          max="20" />
    <goal name="ProgrammingInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Teamwork"
                      title="Teamwork"
                      weight="1.0"
                      >
    <goal name="TeamIntegration"
          title="Team Integration"
          min="1"
          max="20" />
    <goal name="Respect"
          title="Respect"
          min="1"
          max="20" />
    <goal name="FocusedEffort"
          title="Focused Effort"
          min="1"
          max="20" />
    <goal name="Participation"
          title="Participation"
          min="1"
          max="20" />
    <goal name="DecisionSolving"
          title="Decision Making and Problem Solving"
          min="1"
          max="20" />
  </subjectiveCategory>

</fll>

=== jjkoletar/fll-sw/src/resources/challenge.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll xmlns="http://www.hightechkids.org"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.hightechkids.org fll.xsd"
     title="FLL 2002 Challenge: City Sights" >

  <Performance>

    <goal name="Windmill"
	  title="Windmill Spun"
	  multiplier="32" />

    <goal name="Barrels"
	  title="Barrels at Base"
	  max="4"
	  multiplier="10" />

    <goal name="Rocks"
	  title="Soccer Rocks Off"
	  max="4"
	  multiplier="8" />

    <goal name="LoopsOff"
	  title="Loops Off"
	  max="4"
	  multiplier="8" />

    <!-- just for tie breakers -->
    <goal name="PenaltyLoops"
	  title="Loops removed as penalties"
	  max="4"
	  multiplier="0" />

    <!-- market -->
    <goal name="MarketOurs"
	  title="Market: Ours in ours"
	  max="12"
	  multiplier="4"
	  initialValue="4" />

    <goal name="MarketRecieved"
	  title="Market: They gave us"
	  max="8"
	  multiplier="4" />

    <goal name="MarketTheirs"
	  title="Market: We gave them"
	  max="8"
	  multiplier="12" />

    <restriction lowerBound="0"
		 upperBound="8">
      <term goal="MarketOurs" />
      <term goal="MarketTheirs" />
      <term goal="PenaltyLoops" />
      <term coefficient="-1"
	    goal="LoopsOff" />
    </restriction>

    <restriction lowerBound="4">
      <term goal="MarketOurs" />
      <term goal="PenaltyLoops" />
    </restriction>

    <goal name="BG"
	  title="Bundles Ground"
	  max="4"
	  multiplier="6" />

    <goal name="B1"
	  title="Bundles 1st"
	  max="4"
	  multiplier="7" />

    <goal name="B2"
	  title="Bundles 2nd"
	  max="4"
	  multiplier="8" />

    <goal name="B3"
	  title="Bundles 3rd"
	  max="4"
	  multiplier="9" />

    <goal name="B4"
	  title="Bundles 4th"
	  max="4"
	  multiplier="10" />

    <restriction lowerBound="0"
		 upperBound="4">
      <term goal="BG" />
      <term goal="B1" />
      <term goal="B2" />
      <term goal="B3" />
      <term goal="B4" />
    </restriction>

    <!-- houses -->
    <goal name="HouseSingle"
	  title="Red Houses: Single"
	  max="3"
	  multiplier="8" />

    <goal name="HouseDouble"
	  title="Red Houses: Double"
	  multiplier="28" />

    <goal name="HouseTriple"
	  title="Red Houses: Triple"
	  multiplier="40" />

    <restriction lowerBound="0"
		 upperBound="3">
      <term goal="HouseSingle" />
      <term coefficient="2"
	    goal="HouseDouble" />
      <term coefficient="3"
	    goal="HouseTriple" />
    </restriction>

    <goal name="Bridge"
	  title="Bridge Down"
	  multiplier="32" />

    <goal name="Bushes"
	  title="Bushes/Trees Down"
	  max="8"
	  multiplier="-4" />

    <goal name="Interference"
	  title="Did the team deliberately interfere with the other team?"
	  multiplier="0" />

    <tiebreaker>
      <test goal="Interference" winner="low" />
      <test goal="PenaltyLoops" winner="low" />
      <test goal="Bushes" winner="low" />
      <test goal="MarketTheirs" winner="high" />
      <test goal="Barrels" winner="high" />
      <test goal="B4" winner="high" />
      <test goal="B3" winner="high" />
      <test goal="B2" winner="high" />
      <test goal="B1" winner="high" />
      <test goal="BG" winner="high" />
      <test goal="MarketOurs" winner="high" />
      <test goal="Windmill" winner="high" />
      <test goal="HouseTriple" winner="high" />
      <test goal="HouseDouble" winner="high" />
      <test goal="HouseSingle" winner="high" />
      <test goal="LoopsOff" winner="high" />
      <test goal="Bridge" winner="high" />
      <test goal="Rocks" winner="high" />
    </tiebreaker>

  </Performance>

  <subjectiveCategory name="InnovativeDesign">
    <goal name="inFunction"
          title="Creativity in Function"
          min="1"
          max="20" />
    <goal name="Uniqueness"
          title="Uniqueness"
          min="1"
          max="20" />
    <goal name="inDesignProcess"
          title="Creativity in Design Process"
          min="1"
          max="20" />
    <goal name="inDesignAndAppearance"
          title="Creativity in Design and Appearance"
          min="1"
          max="20" />
    <goal name="OverallCreativity"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="RobustDesign">
    <goal name="Structural"
          title="Structural Design"
          min="1"
          max="20" />
    <goal name="Locomotion"
          title="Locomotion"
          min="1"
          max="20" />
    <goal name="Manipulation"
          title="Manipulation"
          min="1"
          max="20" />
    <goal name="Navigation"
          title="Navigation"
          min="1"
          max="20" />
    <goal name="OverallDesign"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>


  <subjectiveCategory name="ResearchQuality"
                      weight="0.6">
    <goal name="Research"
          title="Research"
          min="1"
          max="20" />
    <goal name="Knowledge"
          title="Knowldege"
          min="1"
          max="20" />
    <goal name="ChallengeSpecific"
          title="Challenge Specific"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="InnovativeSolution"
                      weight="0.2">
    <goal name="PresentationInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="CreativePresentation"
                      weight="0.2">
    <goal name="Presentation"
          title="Presentation"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Programming">
    <goal name="Language"
          title="Language used">
      <value>RIS</value>
      <value>RoboLab</value>
      <value>Unknown</value>
    </goal>
    <goal name="UseOfLanguage"
          title="Use of language"
          min="1"
          max="20" />
    <goal name="Modularity"
          title="Modularity/Absraction"
          min="1"
          max="20" />
    <goal name="SensorControl"
          title="Sensor Control"
          min="1"
          max="20" />
    <goal name="Design"
          title="Design"
          min="1"
          max="20" />
    <goal name="ProgrammingInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Teamwork">
    <goal name="TeamIntegration"
          title="Team Integration"
          min="1"
          max="20" />
    <goal name="Respect"
          title="Respect"
          min="1"
          max="20" />
    <goal name="FocusedEffort"
          title="Focused Effort"
          min="1"
          max="20" />
    <goal name="Consideration"
          title="Participation"
          min="1"
          max="20" />
    <goal name="DecisionSolving"
          title="Decision Making and Problem Solving"
          min="1"
          max="20" />
  </subjectiveCategory>

</fll>
