=== jjkoletar/fll-sw/scoring/src/resources/fll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://www.hightechkids.org"
            xmlns="http://www.hightechkids.org"
            elementFormDefault="qualified" >
  <xsd:element name="fll">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Performance" />
        <xsd:element ref="subjectiveCategory" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="title" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Performance">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:sequence maxOccurs="unbounded">
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="goal" maxOccurs="unbounded" />
          </xsd:sequence>
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="restriction" maxOccurs="unbounded" />
          </xsd:sequence>
          <xsd:element ref="tiebreaker" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>
      </xsd:sequence>
      <xsd:attribute name="minimumScore" type="xsd:integer" default="0">
        <xsd:annotation>
          <xsd:documentation>minimum score allowed in the performance scoring</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="weight" type="xsd:float" default="1.0">
        <xsd:annotation>
          <xsd:documentation>
	    Weight this category has.  Should be a number between 0 and 1.
	  </xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="subjectiveCategory">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
          <xsd:element ref="goal" maxOccurs="unbounded" />
        </xsd:sequence>
      </xsd:sequence>
      <xsd:attribute name="name" type="databaseName" use="required" />
      <xsd:attribute name="title" type="xsd:string" use="required" />

      <xsd:attribute name="weight" type="xsd:float" default="1.0">
        <xsd:annotation>
          <xsd:documentation>
	    Weight this category has.  Should be a number between 0 and 1.
	  </xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="goal">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="value" type="databaseName" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="databaseID" use="required" />

      <xsd:attribute name="title" type="xsd:string" use="required" />

      <xsd:attribute name="description" type="xsd:string" />

      <xsd:attribute name="min" type="xsd:integer" default="0">
        <xsd:annotation>
	  <xsd:documentation>ignored if enumerated values exist</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="max" type="xsd:integer" default="1">
        <xsd:annotation>
	  <xsd:documentation>ignored if enumerated values exist</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="multiplier" type="xsd:integer" default="1">
        <xsd:annotation>
	  <xsd:documentation>ignored for subjective goals</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

      <xsd:attribute name="initialValue" type="xsd:integer" default="0">
        <xsd:annotation>
	  <xsd:documentation>ignored for subjective goals</xsd:documentation>
        </xsd:annotation>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>

  <xsd:element name="restriction">
    <xsd:annotation>
      <xsd:documentation>lower bound and upper bound are inclusive</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="term" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="lowerBound" type="xsd:integer" default="-512" />
      <xsd:attribute name="upperBound" type="xsd:integer" default="512" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="term">
    <xsd:complexType>
      <xsd:attribute name="coefficient" type="xsd:integer" default="1" />
      <xsd:attribute name="goal" type="xsd:IDREF" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tiebreaker">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="test" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="goal" type="xsd:IDREF" use="required" />
            <xsd:attribute name="winner" type="highlow" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="databaseName">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\p{L}[\p{L}\p{Nd}]*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="databaseID">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="\p{L}[\p{L}\p{Nd}]*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="highlow">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="high" />
      <xsd:enumeration value="low" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== jjkoletar/fll-sw/scoring/src/resources/challenge-state-2003.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll xmlns="http://www.hightechkids.org"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.hightechkids.org fll.xsd"
     title="FLL 2002 Challenge: City Sights" >

  <Performance weight="0.25">

    <goal name="exit_base"
	  title="Exit the Tetrahedron Base"
	  multiplier="39" />

    <goal name="launch_canister"
	  title="Launch the Sample Canister">
      <value score="39">Canister Launched</value>
      <value score="27">Launcher Actived Empty</value>
    </goal>

    <goal name="clear_solar"
	  title="Clear the Solar Panel">
      <value score="43">Dust Completly Cleared</value>
      <value score="31">Dust Partially Cleared</value>
    </goal>

    <goal name="habitation_modules"
	  title="Connect the 180 and 90 Habitation Modules">
      <value score="49">V-Shaped Module COnnection</value>
      <value score="31">Two Module Connections In Line</value>
      <value score="27">One Module Connection</value>
    </goal>

    <goal name="alliance_habitation"
	  title="Complete the Alliance Habitation Module"
	  multiplier="43" />

    <goal name="free_rover"
	  title="Free the Rover">
      <value score="43">Rover In Base</value>
      <value score="31">Rover Off Dune + On Wheels</value>
    </goal>

    <goal name="ice_core"
	  title="Move Ice Cores to Base">
      <value score="49">3 Ice Cores in Base</value>
      <value score="31">2 Ice Cores in Base</value>
      <value score="27">1 Ice Cores in Base</value>
    </goal>

    <goal name="boulders_in_circle"
	  title="Boulders In The Launch Circle"
          max="4"
	  multiplier="14" />

    <goal name="boulders_outside_circle"
	  title="Boulders On the Field Outside The Launch Circle"
          max="4"
	  multiplier="8" />

    <goal name="vehicle"
	  title="All Terrain Vehicle Test"
	  multiplier="39" />

    <restriction lowerBound="0"
		 upperBound="4">
      <term goal="boulders_in_circle" />
      <term goal="boulders_outside_circle" />
    </restriction>

    <tiebreaker>
    </tiebreaker>

  </Performance>

  <subjectiveCategory name="InnovativeDesign"
                      title="Innovative Design"
                      weight="0.0"
                      >
    <goal name="inFunction"
          title="Creativity in Function"
          min="1"
          max="20" />
    <goal name="Uniqueness"
          title="Uniqueness"
          min="1"
          max="20" />
    <goal name="inDesignProcess"
          title="Creativity in Design Process"
          min="1"
          max="20" />
    <goal name="inDesignAndAppearance"
          title="Creativity in Design and Appearance"
          min="1"
          max="20" />
    <goal name="OverallCreativity"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="RobustDesign"
                      title="Robust Design"
                      weight="0.125"
                      >
    <goal name="Structural"
          title="Structural Design"
          min="1"
          max="20" />
    <goal name="Locomotion"
          title="Locomotion"
          min="1"
          max="20" />
    <goal name="Manipulation"
          title="Manipulation"
          min="1"
          max="20" />
    <goal name="Navigation"
          title="Navigation"
          min="1"
          max="20" />
    <goal name="OverallDesign"
          title="Overall Design and Integration"
          min="1"
          max="20" />
  </subjectiveCategory>


  <subjectiveCategory name="ResearchQuality"
                      title="Research Quality"
                      weight="0.15"
                      >
    <goal name="Research"
          title="Research"
          min="1"
          max="20" />
    <goal name="Knowledge"
          title="Knowldege"
          min="1"
          max="20" />
    <goal name="ChallengeSpecific"
          title="Challenge Specific"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="InnovativeSolution"
                      title="Innovative Solution"
                      weight="0.05"
                      >
    <goal name="PresentationInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="CreativePresentation"
                      title="Creative Presentation"
                      weight="0.05"
                      >
    <goal name="Presentation"
          title="Presentation"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Programming"
                      title="Programming"
                      weight="0.125"
                      >
    <goal name="Language"
          title="Language used">
      <value>RIS</value>
      <value>RoboLab</value>
      <value>Unknown</value>
    </goal>
    <goal name="UseOfLanguage"
          title="Use of language"
          min="1"
          max="20" />
    <goal name="Modularity"
          title="Modularity/Absraction"
          min="1"
          max="20" />
    <goal name="SensorControl"
          title="Sensor Control"
          min="1"
          max="20" />
    <goal name="Design"
          title="Design"
          min="1"
          max="20" />
    <goal name="ProgrammingInGeneral"
          title="In General"
          min="1"
          max="20" />
  </subjectiveCategory>

  <subjectiveCategory name="Teamwork"
                      title="Teamwork"
                      weight="0.25"
                      >
    <goal name="TeamIntegration"
          title="Team Integration"
          min="1"
          max="20" />
    <goal name="Respect"
          title="Respect"
          min="1"
          max="20" />
    <goal name="FocusedEffort"
          title="Focused Effort"
          min="1"
          max="20" />
    <goal name="Consideration"
          title="Participation"
          min="1"
          max="20" />
    <goal name="DecisionSolving"
          title="Decision Making and Problem Solving"
          min="1"
          max="20" />
  </subjectiveCategory>

</fll>

=== jjkoletar/fll-sw/challenge-descriptors/challenge-region-2006.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll title="FLL 2006 Challenge: Nano Quest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fll.xsd">

  <Performance minimumScore="0" weight="1.0">

    <goal name="move_atoms" title="Individual Atom Manipulation">
      <value score="40" title="8 red &amp; 0 to 5 white" value="atoms_high"/>
      <value score="30" title="8 red &amp; 6 to 7 white" value="atoms_low"/>
      <value score="0" title="Fewer than 8 red" value="atoms_none"/>
    </goal>

    <goal name="smell_off_plate" title="Molecules off Paper Plate"
      min="0"
      max="2"
      multiplier="5"
      />
    <goal name="smell_head" title="Molecules on Head or Neck"
      min="0"
      max="2"
      multiplier="15"
      />
    <restriction lowerBound="0" upperBound="2" message="There are a maximum of 2 molecules on the table">
      <term coefficient="1" goal="smell_off_plate"/>
      <term coefficient="1" goal="smell_head"/>
    </restriction>

    <goal name="dirt_trap" title="Dirt Trap on Mark"
      multiplier="15"
      />

    <goal name="dumper" title="Dirt Dumper Empty"
      multiplier="15"
      />

    <goal name="dirt_in_trap" title="Dirt in Dirt Trap"
      multiplier="5"
      max="8"
      />

    <goal name="dirt_elsewhere" title="Dirt Elsewhere"
      multiplier="3"
      max="8"
      />
    <restriction lowerBound="0" upperBound="3" message="There are a maximum of 3 dirt pieces on the table">
      <term coefficient="1" goal="dirt_in_trap"/>
      <term coefficient="1" goal="dirt_elsewhere"/>
    </restriction>

    <goal name="atomic_force" title="Free the Probe's Nanotip"
      multiplier="40"
      />

    <goal name="self_assembly" title="Self-alignment of Atoms"
      multiplier="30"
      />

    <goal name="smart_medicine" title="Buckyball in the Red/Yellow Channel"
      multiplier="50"
      />

    <goal name="nanotube_strength" title="Nanotube Strength">
      <value score="40" title="Supported by Cable" value="supported_by_cable"/>
      <value score="20" title="Truck on Frame" value="truck_on_frame"/>
      <value score="0" title="None" value="none"/>
    </goal>

    <goal name="molecular_motor" title="Deliver ATP molecule"
      multiplier="40"
      />

    <goal name="space_elevator" title="Operate Space Elevator"
      multiplier="40"
      />

    <goal name="fairness" title="Fairness Bonus: RCX completes 3 missions, NXT completes 6"
      multiplier="20"
      />

    <tiebreaker>
      <test goal="fairness" winner="high"></test> 
    </tiebreaker>

  </Performance>

  <subjectiveCategory name="teamwork" title="Teamwork" weight="1.0">
    <goal initialValue="0" max="10" min="1" multiplier="1" name="roles" title="Roles and Responsibilities"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="professionalism" title="Gracious Professionalism"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="dynamics" title="Problem Solving &amp; Team Dynamics &amp; Communications"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="confidence" title="Confidence &amp; Enthusiasm"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="fll_values" title="FLL Values"></goal>
  </subjectiveCategory>

  
  <subjectiveCategory name="robustdesign" title="Robust Design" weight="0.5">
    <goal initialValue="0" max="10" min="1" multiplier="1" name="strategy" title="Strategy, Process, Problem Solving"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="locomotion" title="Locomotion and Navigation"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="design_kids" title="Kids Did the Work"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="structural" title="Structural"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="overall_design" title="Overall Design"></goal>
  </subjectiveCategory>


  <subjectiveCategory name="programming" title="Robust Programming" weight="0.5">
    <goal initialValue="0" max="10" min="1" multiplier="1" name="useoflanguage" title="Use of Language"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="modularity" title="Modularity/Abstraction"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="sensorcontrol" title="Sensor Control"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="design" title="Design"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="programming_kids" title="Kids Did the Work"></goal>
  </subjectiveCategory>

  <subjectiveCategory name="research" title="Research Project Assessment" weight="1.0">
    <goal initialValue="0" max="10" min="1" multiplier="1" name="questions" title="Questions, Language Use"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="completeness" title="Completeness, Teamwork"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="background" title="Background, Data, and Graphics"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="analysis" title="Analysis and Conclusions"></goal>
    <goal initialValue="0" max="10" min="1" multiplier="1" name="style" title="Style"></goal>
  </subjectiveCategory>

  
</fll>

=== jjkoletar/fll-sw/challenge-descriptors/drag-race-2009.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll title="Science of Speed: 2008"
 bracketSort="ALPHA_TEAM"
  winner='LOW'
 revision="$Rev: 351 $"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="fll.xsd"
 >

  <Performance minimumScore="-20" weight="1.0">

  <goal name="seconds" title="Seconds" max="10"/>
  <goal name="tenths" title="Tenths" max="10"/>
  <goal name="hundredths" title="Hundreths" max="10"/>
  <goal name="thousandths" title="Thousandths" max="10"/>
  
  <tiebreaker>
  <!-- should be empty, but not allowed by the schema -->
   <test winner='LOW'>
     <term goal='seconds' scoreType='computed'/>
   </test>
  </tiebreaker>

 </Performance>

</fll>

=== jjkoletar/fll-sw/challenge-descriptors/challenge-region-2008.xml
<?xml version="1.0" encoding="UTF-8"?>
<fll title="FLL 2008 Challenge: Climate Connections"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="fll.xsd">

 <!-- $Rev: 351 $ -->

 <Performance minimumScore="0" weight="1.0">

  <goal name="bury_cabon_dioxide" title="Bury Carbon Dioxide"
   multiplier="5" max="4" />
    <!-- FIXME need to know max -->
    
  <goal name="construct_levees_red"
   title="Construct Levees touching RED" multiplier="5"
      max="8" />

  <goal name="construct_levees_green"
   title="Construct Levees touching GREEN" multiplier="4"
      max="8" />
    <restriction lowerBound="0" upperBound="8"
      message="There are only 3 levees on the table">
      <term goal="construct_levees_red" scoreType="raw"/>
      <term goal="construct_levees_green" scoreType="raw"/>
    </restriction>
    
  <goal name="test_levees" title="Test Levees"
      multiplier="15" />

  <goal name="raise_flood_barrier" title="Raise The Flood Barrier" multiplier="15" />

  <goal name="elevate_house" title="Elevate The House" multiplier="25" />

  <goal name="turn_off_lights" title="Turn Off The Lights" multiplier="20"/>

  <goal name="open_window" title="Open A Window"
   multiplier="25"/>

  <goal name="get_people_together_pink" title="Three or more red/white citizens touching the pink"
   multiplier="10" />

  <goal name="get_people_together_green" title="Three or more blue/gray leaders touching the green mountain and/or city"
   multiplier="10" />

  <goal name="get_people_together_research" title="Three or more black/white scientists touching the research area"
   multiplier="10" />
    
  <goal name="find_agreement" title="Align the Arrows"
   multiplier="40" />

  <goal name="fund_research" title="Fund Research or Corrective Action" multiplier="15" />

  <goal name="deliver_machine" title="Deliver An Ice Core Drilling Machine" multiplier="20" />

  <goal name="drill_assembly" title="Drill Assembly Raised Completely Vertical" multiplier="10" />
    
  <goal name="extract_sample" title="Extract An Ice Core Sample" multiplier="20" />

  <goal name="ice_core_base" title="Ice Core IN Base" multiplier="10" />

  <goal name="deliver_buoy" title="Deliver An Ice Buoy" multiplier="25" />

  <goal name="insulate_house" title="Insulte A House"
   multiplier="10" />

  <goal name="ride_bicycle" title="Ride A Bicycle" multiplier="10" />

  <goal name="telecommute" title="Telecommute And Research" multiplier="10" />

  <goal name="study_wildlife_bear" title="Study Wildlife - Bear"
      initialValue="0">
      <value score="15" title="Upright" value="upright"/>
      <value score="10" title="Sleeping" value="sleeping"/>
      <value score="0" title="None" value="none"/>
  </goal>

  <goal name="study_wildlife_snowmobile" title="Study Wildlife - Snowmobile" multiplier="10" />
    
    <goal name="beat_clock" title="Beat the Clock"
      initialValue="0"
      >
      <value score="15" title="Research Area" value="research_area"/>
      <value score="10" title="Yellow Grid Area" value="yellow_area"/>
      <value score="0" title="None" value="none"/>
    </goal>

    <!-- FIXME need tiebreaker -->
  <tiebreaker>
   <test winner='high'>
     <term goal='beat_clock' scoreType='computed'/>
   </test>
  </tiebreaker>

 </Performance>

 <subjectiveCategory name="teamwork" title="Teamwork" weight="1.0">
  <goal initialValue="0" max="20" min="0" multiplier="1" name="roles"
   title="Roles and Responsibilities">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="professionalism" title="Gracious Professionalism">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1" name="dynamics"
   title="Problem Solving &amp; Team Dynamics &amp; Communications">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="confidence" title="Confidence &amp; Enthusiasm">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="fll_values" title="FLL Values">
  </goal>
 </subjectiveCategory>


 <subjectiveCategory name="robustdesign" title="Design"
  weight="0.5">
  <goal initialValue="0" max="20" min="0" multiplier="1" name="strategy"
   title="Strategy, Process, Problem Solving">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="locomotion" title="Locomotion and Navigation">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="design_kids" title="Kids Did the Work">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="structural" title="Structural">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="overall_design" title="Overall Design">
  </goal>
 </subjectiveCategory>


 <subjectiveCategory name="programming" title="Programming"
  weight="0.5">
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="useoflanguage" title="Use of Language">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="modularity" title="Modularity/Abstraction">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="sensorcontrol" title="Sensor Control">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1" name="design"
   title="Design">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="programming_kids" title="Kids Did the Work">
  </goal>
 </subjectiveCategory>

 <subjectiveCategory name="research" title="Research Project Assessment"
  weight="1.0">
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="questions" title="Questions, Language Use">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="completeness" title="Completeness, Teamwork">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1"
   name="background" title="Background, Data, and Graphics">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1" name="analysis"
   title="Analysis and Conclusions">
  </goal>
  <goal initialValue="0" max="20" min="0" multiplier="1" name="style"
   title="Style">
  </goal>
 </subjectiveCategory>


</fll>
